version: '3.8'

services:
  # Base de Datos
  db:
    image: postgres:17
    container_name: sprintix-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypass
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - sprintix-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d mydb"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Tu API Spring Boot (Unificada)
  api:
    build: .  # <-- Construye la carpeta ACTUAL
    container_name: sprintix-api
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_NAME=mydb
      - DB_USER=myuser
      - DB_PASSWORD=mypass
    networks:
      - sprintix-network
    depends_on:
      db:
        condition: service_healthy

networks:
  sprintix-network:
    driver: bridge

volumes:
  pgdata: